apiVersion: sample.authentik.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: example
  namespace: default
spec:
  forProvider:
    configurableField: test
  providerConfigRef:
    name: example
    kind: ProviderConfig
---
apiVersion: sample.authentik.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: cluster-example
  namespace: default
spec:
  forProvider:
    configurableField: test
  providerConfigRef:
    name: example
    kind: ClusterProviderConfig
